---
defaultMaxDepth: 10
defaultLanguage: "en"
updateCheck: true
vertxOptions:
    workerPoolSize: 20
    eventPoolSize: 2
tempDirectory: "data/tmp"
pluginDirectory: "plugins"
nodeName: "Questing Seedot"
httpServer:
    port: 8080
    host: "0.0.0.0"
    corsAllowedOriginPattern: ""
    corsAllowCredentials: false
    enableCors: false
    ssl: false
    certPath: "config/cert.pem"
    keyPath: "config/key.pem"
monitoring:
    enabled: true
    port: 8081
    host: "127.0.0.1"
cluster:
    enabled: false
    vertxPort: 0
storage:
    directory: "data/graphdb"
    backupDirectory: "data/backup"
    exportDirectory: "data/export"
    startServer: false
    parameters: {}
search:
    url: "http://localhost:9200"
    timeout: 8000
    startupTimeout: 45
    startEmbedded: true
    embeddedArguments: "-Xms512m -Xmx512m -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75\
    \ -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -client -Xss1m -Djava.awt.headless=true\
    \ -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true\
    \ -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0\
    \ -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -XX:+HeapDumpOnOutOfMemoryError"
    prefix: "mesh-"
    bulkLimit: 2000
    eventBufferSize: 1000
    bulkDebounceTime: 2000
    idleDebounceTime: 100
    retryInterval: 5000
    waitForIdle: true
upload:
    byteLimit: 262144000
    directory: "data/binaryFiles"
    tempDirectory: "data/tmp/file-uploads"
    parserLimit: 40000
security:
    tokenExpirationTime: 3600
    keystorePassword: "0adbb0f6710d49b39bb0f6710df9b37a"
    keystorePath: "config/keystore.jceks"
    algorithm: "HS256"
    enableAnonymousAccess: true
    oauth2:
        enabled: false
        mapperScriptDevMode: false
image:
    imageCacheDirectory: "data/binaryImageCache"
    maxWidth: 2048
    maxHeight: 2048
    jpegQuality: 0.95
    resampleFilter: "LANCZOS"
content:
    autoPurge: true
