version: '3.7'
services:
  getmesh:
    image: co_gov_cancilleria/getmesh:0.1
    ports:
      - 8080:8080
    environment:
      MESH_DELAY_RESTORE: 90
      MESH_ADMIN_USER: admin
      MESH_ADMIN_PASSWORD: admin
    deploy:
      restart_policy:
        condition: unless-stopped
